# Netlify configuration

[build]
  command = "npm run build"
  publish = ".next"

# Production context (main branch)
[context.production]
  environment = { CONTEXT = "production" }

# Deploy preview context  
[context.deploy-preview]
  environment = { CONTEXT = "deploy-preview" }
  
# Branch deploy context
[context.branch-deploy]
  environment = { CONTEXT = "branch-deploy" }

# Headers for non-production deploys
[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

# Override for production
[context.production.headers]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "index, follow"